# Generated by Django 3.2.6 on 2021-08-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('emailID', models.CharField(max_length=100)),
                ('phno', models.BigIntegerField()),
                ('dob', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('aadhar_no', models.BigIntegerField()),
            ],
        ),
    ]
