# Generated by Django 3.2.6 on 2021-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_details', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('manufacturing_date', models.CharField(max_length=50)),
                ('expiry_date', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
