# Generated by Django 3.2.6 on 2021-08-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sid', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('phno', models.BigIntegerField()),
            ],
        ),
    ]
